apiVersion: apps/v1
kind: Deployment
metadata:
  name: butlerservice
  labels:
    app: butlerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: butlerservice
  template:
    metadata:
      labels:
        name: butlerservice
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/butlerservice"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: butlerservice
